### ISSUE TITLE
Miscellaneous task list

### ISSUE THREAD

**Issue by willpearse** [pearselab/tyrell#1]
**Data sources**
  - [x] _LMIC Rt estimates_
  - [x] _CDS AR5 monthly data_
  - [x] Move to using monthly temperature data from CDS?
  - [x] _CDS AR5 daily data_
  - [x] UV data (???)
  - [ ] Pollution data (???)
  - [x] One of the population US state estimates is NA; filling in with unbiased median now but need to address
  - [x] Population density (from Michael's stuff)
  - [x] Corrections of environment for human population density
  - [ ] Repeat all the above for admin-2 (at least in Italy)
  - [ ] SD of all estimates per unit (--> how reliable the number is)
  - [x] `ext-data` folder for non-scriptable data (and maybe caches of things, like nxt-strain?)
  - [x] Fix LMIC download.

**Rt external validation models**
  - [x] _US ~ everything_
  - [x] Europe ~ everything
  - [x] _LMIC ~ everything_
  - [ ] Account for uncertainty in estimates?
  - [x] Check they're being done with R0 values and/or harmonise for lockdown somehow and/or repeat the above after lockdowns

**(Bayesian) model integration**
  - [x] _Make final decision on env term placement_
  - [x] Europe
  - [x] Brazil
  - [x] Italy
  - [x] _US_
  - [x] Scope out LMIC models
  - [ ] Fit LMIC

**Miscellaneous**
  - [ ] Revisit whether population density should be at 15 or 2.5 (could need to be lower for European data? admin2?)
  - [ ] LMIC download scraper will need Selenium because the website loads raw Javascript.
  - [ ] Drop the `wget` from the PHE case data download
  - [ ] humidity data will likely need to generate year_month names from the length of the data as more data gets added through time (add to update_data as well?)
  - [x] Check throughout package for use of `raster::extract` instead of `velox::extract`
  - [ ] Scope out new mobility models from Pierre
  - [ ] Fit new mobility models
  - [ ] IHME raw data download will delete any new folders (recursively!) in `raw-data`
  - [ ] Merge timestamping and meta-data information? Or, perhaps better, add `metadata.csv` file separate from dating
  - [ ] Load more R0 estimates
  - [x] Load genetic data (difficult because of nextstrain using JavaScript
  - [x] Update task vs. download all new data task
  - [x] Consider what the default task should be?
  - [ ] Make NextStrain loading less clunky
  - [ ] Make WHO updating
  - [ ] Change worldclim-countries to be a CSV?
  - [x] Do we need to download the GADM data if we can use the package Michael uses in his WORLDCLIM script?
  - [x] Missing the state-level estimates in the DENVfoiMaps loading (length error?)
  - [ ] mperial models run, but they may not be the best way of running them...
  - [ ] Imperial Brazil mode is in debug mode by default, and can't be turned off without altering the script (which is fine, but I'd rather not grep it...)
  - [ ] Make downloading cleaner when the dependencies have changed (e.g., when there's a new Imperial model when there's a new one and the older folders cause problems unzipping etc.)
  - [ ] Consider Rich's cool new way of integrating
  - [ ] Setup new Imperial server
  - [ ] Make rake also compile the manuscript?

**Comment by willpearse** [comment]
- [ ] Make NextStrain loading less clunky

**Comment by willpearse** [comment]
- [ ] Imperial models run, but they may not be the best way of running them...
- [ ] Imperial Brazil mode is in debug mode by default, and can't be turned off without altering the script (which is fine, but I'd rather not grep it...)

**Comment by willpearse** [comment]
- [ ] Make WHO updating

**Comment by willpearse** [comment]
- [ ] Make downloading cleaner when the dependencies have changed (e.g., when there's a new Imperial model when there's a new one and the older folders cause problems unzipping etc.)

**Comment by willpearse** [comment]
- [ ] Change `worldclim-countries` to be a CSV?
- [ ] Do we need to download the GADM data if we can use the package Michael uses in his WORLDCLIM script?

**Comment by willpearse** [comment]
- [ ] Missing the state-level estimates in the DENVfoiMaps loading (length error?)
